name: Tests

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: pre-commit/action@v3.0.1

  Tests:
    needs: Linting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.12]
        os: [ubuntu-latest]
        env: [ci/envs/312-tests.yaml]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: ${{ matrix.env }}

      - name: Install coastal dynamics as editable package
        run: |
          python -m pip install -e .

      - name: Check and Log Environment
        run: |
          python -V
          micromamba info
          python -c "import coastpy; print(coastpy.__version__)"

      # We currently do not have any tests yet
      # - name: Test with pytest
      #   run: pytest
